## Projets de Fin de Formation
# (Formation en Intelligence Artificielle)


Problème 1: Prédiction sur les données Tabulaires

Le problème1 est un problème d apprentissage supervisé (classification) dont nous allons prédire sur le score final des apprenants (Pass,Withdrawn,Fail,Distinction) dont la traduction en français est ( Passer, Retiré, Échouer, Distinction)
d’une formation en ligne.Identifier à quelle catégorie appartient les apprenants. 

In [32]:
#Importation des libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, mean_squared_error, precision_score, recall_score, confusion_matrix, f1_score
from scipy import stats
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.multioutput import MultiOutputClassifier, MultiOutputRegressor
from sklearn.multiclass import OutputCodeClassifier

In [3]:
#Chargement du dataset
data = pd.read_csv("studentInfo.csv")

In [4]:
data1 = pd.read_csv("courses.csv")

In [5]:
data.shape

(32593, 12)

In [6]:
data.head()

code_module code_presentation  id_student gender                region  \
0         AAA             2013J       11391      M   East Anglian Region   
1         AAA             2013J       28400      F              Scotland   
2         AAA             2013J       30268      F  North Western Region   
3         AAA             2013J       31604      F     South East Region   
4         AAA             2013J       32885      F  West Midlands Region   

       highest_education imd_band age_band  num_of_prev_attempts  \
0       HE Qualification  90-100%     55<=                     0   
1       HE Qualification   20-30%    35-55                     0   
2  A Level or Equivalent   30-40%    35-55                     0   
3  A Level or Equivalent   50-60%    35-55                     0   
4     Lower Than A Level   50-60%     0-35                     0   

   studied_credits disability final_result  
0              240          N         Pass  
1               60          N         Pass  
2               60          Y    Withdrawn  
3               60          N         Pass  
4               60          N         Pass

In [7]:
data.describe()

id_student  num_of_prev_attempts  studied_credits
count  3.259300e+04          32593.000000     32593.000000
mean   7.066877e+05              0.163225        79.758691
std    5.491673e+05              0.479758        41.071900
min    3.733000e+03              0.000000        30.000000
25%    5.085730e+05              0.000000        60.000000
50%    5.903100e+05              0.000000        60.000000
75%    6.444530e+05              0.000000       120.000000
max    2.716795e+06              6.000000       655.000000

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64 
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              31482 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64 
 9   studied_credits       32593 non-null  int64 
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.0+ MB


In [9]:
data.isnull().sum()

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

In [10]:
data.dtypes

code_module             object
code_presentation       object
id_student               int64
gender                  object
region                  object
highest_education       object
imd_band                object
age_band                object
num_of_prev_attempts     int64
studied_credits          int64
disability              object
final_result            object
dtype: object

In [11]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   code_module                 22 non-null     object
 1   code_presentation           22 non-null     object
 2   module_presentation_length  22 non-null     int64 
dtypes: int64(1), object(2)
memory usage: 656.0+ bytes


In [12]:
data1.describe()

module_presentation_length
count                   22.000000
mean                   255.545455
std                     13.654677
min                    234.000000
25%                    241.000000
50%                    261.500000
75%                    268.000000
max                    269.000000

In [13]:
data1.head()

code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240

In [14]:
#pretraitement des données 
m = data.loc[:, ["code_module","code_presentation","gender","region","highest_education","imd_band","age_band","disability","final_result"]]

In [15]:
m.head()

code_module code_presentation gender                region  \
0         AAA             2013J      M   East Anglian Region   
1         AAA             2013J      F              Scotland   
2         AAA             2013J      F  North Western Region   
3         AAA             2013J      F     South East Region   
4         AAA             2013J      F  West Midlands Region   

       highest_education imd_band age_band disability final_result  
0       HE Qualification  90-100%     55<=          N         Pass  
1       HE Qualification   20-30%    35-55          N         Pass  
2  A Level or Equivalent   30-40%    35-55          Y    Withdrawn  
3  A Level or Equivalent   50-60%    35-55          N         Pass  
4     Lower Than A Level   50-60%     0-35          N         Pass

In [16]:
#Encodage One_Hot
dummy_m = pd.get_dummies(m["final_result"])

In [17]:
df = m.drop("final_result", axis=1)

In [18]:
data_x = m.loc[:, ["code_module","code_presentation","gender","region","highest_education","imd_band","age_band","disability"]]

In [19]:
data_x

code_module code_presentation gender                region  \
0             AAA             2013J      M   East Anglian Region   
1             AAA             2013J      F              Scotland   
2             AAA             2013J      F  North Western Region   
3             AAA             2013J      F     South East Region   
4             AAA             2013J      F  West Midlands Region   
...           ...               ...    ...                   ...   
32588         GGG             2014J      F                 Wales   
32589         GGG             2014J      F   East Anglian Region   
32590         GGG             2014J      F          South Region   
32591         GGG             2014J      F     South East Region   
32592         GGG             2014J      F      Yorkshire Region   

           highest_education imd_band age_band disability  
0           HE Qualification  90-100%     55<=          N  
1           HE Qualification   20-30%    35-55          N  
2      A Level or Equivalent   30-40%    35-55          Y  
3      A Level or Equivalent   50-60%    35-55          N  
4         Lower Than A Level   50-60%     0-35          N  
...                      ...      ...      ...        ...  
32588     Lower Than A Level    10-20     0-35          N  
32589     Lower Than A Level   40-50%    35-55          N  
32590  A Level or Equivalent   20-30%     0-35          Y  
32591     Lower Than A Level  90-100%    35-55          N  
32592       HE Qualification   50-60%    35-55          N  

[32593 rows x 8 columns]

In [20]:
encoder1 = OneHotEncoder(categories='auto')
x = encoder1.fit_transform(data_x)
p = pd.DataFrame(x.toarray())

In [21]:
df = pd.concat([p, dummy_m], axis=1)
df

0    1    2    3    4    5    6    7    8    9  ...   41   42   43  \
0      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
1      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0   
2      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0   
3      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0   
4      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
32588  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
32589  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
32590  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
32591  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
32592  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   

        44   45   46  Distinction  Fail  Pass  Withdrawn  
0      1.0  1.0  0.0            0     0     1          0  
1      0.0  1.0  0.0            0     0     1          0  
2      0.0  0.0  1.0            0     0     0          1  
3      0.0  1.0  0.0            0     0     1          0  
4      0.0  1.0  0.0            0     0     1          0  
...    ...  ...  ...          ...   ...   ...        ...  
32588  0.0  1.0  0.0            0     1     0          0  
32589  0.0  1.0  0.0            1     0     0          0  
32590  0.0  0.0  1.0            0     0     1          0  
32591  0.0  1.0  0.0            0     0     0          1  
32592  0.0  1.0  0.0            1     0     0          0  

[32593 rows x 51 columns]

In [22]:
x = df.iloc[:, :-4].values

In [40]:
X = np.array(df.iloc[:, :-4])
y = df[["Distinction"]]
# y = df[["Fail"]]
# y = df[["Pass"]]
# y = df[["Withdrawn"]]
y

Distinction
0                0
1                0
2                0
3                0
4                0
...            ...
32588            0
32589            1
32590            0
32591            0
32592            1

[32593 rows x 1 columns]

In [41]:
#Entrainemment des données train et test
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state =5 )
# print(Y_test)
print(Y_test)

       Distinction
1081             0
8553             0
30036            0
1523             0
22546            0
...            ...
8852             0
4088             0
20865            0
29247            0
957              0

[6519 rows x 1 columns]


In [42]:
df.describe()

0             1             2             3             4  \
count  32593.000000  32593.000000  32593.000000  32593.000000  32593.000000   
mean       0.022950      0.242659      0.136041      0.192434      0.090019   
std        0.149745      0.428697      0.342838      0.394218      0.286214   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

                  5             6             7             8             9  \
count  32593.000000  32593.000000  32593.000000  32593.000000  32593.000000   
mean       0.238149      0.077747      0.143712      0.271377      0.239438   
std        0.425957      0.267777      0.350803      0.444677      0.426747   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      1.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       ...            41            42            43            44  \
count  ...  32593.000000  32593.000000  32593.000000  32593.000000   
mean   ...      0.034087      0.703955      0.289418      0.006627   
std    ...      0.181456      0.456518      0.453499      0.081139   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      1.000000      0.000000      0.000000   
75%    ...      0.000000      1.000000      1.000000      0.000000   
max    ...      1.000000      1.000000      1.000000      1.000000   

                 45            46   Distinction          Fail          Pass  \
count  32593.000000  32593.000000  32593.000000  32593.000000  32593.000000   
mean       0.902924      0.097076      0.092781      0.216365      0.379253   
std        0.296066      0.296066      0.290129      0.411773      0.485209   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      0.000000      0.000000      0.000000   
50%        1.000000      0.000000      0.000000      0.000000      0.000000   
75%        1.000000      0.000000      0.000000      0.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

          Withdrawn  
count  32593.000000  
mean       0.311601  
std        0.463155  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        1.000000  
max        1.000000  

[8 rows x 51 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 51 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   0            32593 non-null  float64
 1   1            32593 non-null  float64
 2   2            32593 non-null  float64
 3   3            32593 non-null  float64
 4   4            32593 non-null  float64
 5   5            32593 non-null  float64
 6   6            32593 non-null  float64
 7   7            32593 non-null  float64
 8   8            32593 non-null  float64
 9   9            32593 non-null  float64
 10  10           32593 non-null  float64
 11  11           32593 non-null  float64
 12  12           32593 non-null  float64
 13  13           32593 non-null  float64
 14  14           32593 non-null  float64
 15  15           32593 non-null  float64
 16  16           32593 non-null  float64
 17  17           32593 non-null  float64
 18  18           32593 non-null  float64
 19  19  

In [44]:
# SVM régularization des paramétres
C = 1.0
g = 3.0
models = (
    svm.SVC(kernel="linear", C=C),
    svm.LinearSVC(C=C, max_iter=10000),
    svm.SVC(kernel="rbf", gamma=g, C=C),
    svm.SVC(kernel="poly", degree=3, gamma="auto", C=C),
)

In [45]:
print(models)

(SVC(kernel='linear'), LinearSVC(max_iter=10000), SVC(gamma=3.0), SVC(gamma='auto', kernel='poly'))


In [47]:
for clf in models:
    clf.fit(X_train, Y_train)
    yhat= clf.predict(X_test)
    print(" -Implementation", clf)
    print("Valeur predite:")
    print(yhat[:5])
    print("Ce qui est attendu:\n",Y_test[:5])

    print("Les métriques", clf)
    mse = mean_squared_error(Y_test, yhat)
    score = clf.score(X_test, Y_test)

C:\Users\BAH\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


 -Implementation SVC(kernel='linear')
Valeur predite:
[0 0 0 0 0]
Ce qui est attendu:
        Distinction
1081             0
8553             0
30036            0
1523             0
22546            0
Les métriques SVC(kernel='linear')


C:\Users\BAH\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


 -Implementation LinearSVC(max_iter=10000)
Valeur predite:
[0 0 0 0 0]
Ce qui est attendu:
        Distinction
1081             0
8553             0
30036            0
1523             0
22546            0
Les métriques LinearSVC(max_iter=10000)


C:\Users\BAH\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


 -Implementation SVC(gamma=3.0)
Valeur predite:
[0 0 0 0 0]
Ce qui est attendu:
        Distinction
1081             0
8553             0
30036            0
1523             0
22546            0
Les métriques SVC(gamma=3.0)


C:\Users\BAH\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


 -Implementation SVC(gamma='auto', kernel='poly')
Valeur predite:
[0 0 0 0 0]
Ce qui est attendu:
        Distinction
1081             0
8553             0
30036            0
1523             0
22546            0
Les métriques SVC(gamma='auto', kernel='poly')
